[package]
name = "cma_es"
version = "0.1.0"
authors = ["Arthur Carcano <>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.21.1"
rand = "0.7.3"
rand_distr = "0.2.2"
num-traits = "0.2.12"